spring.application.name=taskmanager

spring.data.mongodb.uri=mongodb+srv://nikhilsingh_db_user:2Sc8krgTHq9db0lI@testdbonline.8l4hjf7.mongodb.net/taskmanagerdb?retryWrites=true&w=majority&appName=TestDBOnline
spring.mvc.format.date=yyyy-MM-dd